[package]
name = "Projekt"
version = "0.1.0"
edition = "2021"

[dependencies]
device_query = "1.1.3"
windows = { version = "0.48", features = ["Win32_UI_WindowsAndMessaging", "Win32_Foundation", "Win32_UI_Input_KeyboardAndMouse"] }
enigo = "0.1.3"
